### ISSUE TITLE
Finish Bevy 0.12 updates

### ISSUE THREAD

**Issue by Seldom-SE** [Seldom-SE/seldom_pixel#5]
- [x] Update to new `bevy_ecs_tilemap` release, when that's available
- [x] Fix `particle` feature
- [x] Fix `state` example

**Comment by TuntematonSotilas** [comment]
Hello, I saw that `bevy_ecs_tilemap` was just release to support bevy 0.12 😉
https://github.com/StarArawn/bevy_ecs_tilemap/releases/tag/v0.12.0
